-- ClickUpTasks — task-files storage policies
-- Prereq: in the Supabase dashboard, Storage → New bucket → name it exactly
--   task-files  and leave "Public bucket" OFF (private). Then run this file.
--
-- These grant any signed-in team member read/write on the bucket. That's fine
-- for a small trusted team; tighten to per-assignment later if needed. Downloads
-- always go through short-lived signed URLs generated by the app.

drop policy if exists "task-files read" on storage.objects;
create policy "task-files read" on storage.objects for select to authenticated
  using (bucket_id = 'task-files');

drop policy if exists "task-files insert" on storage.objects;
create policy "task-files insert" on storage.objects for insert to authenticated
  with check (bucket_id = 'task-files');

drop policy if exists "task-files delete" on storage.objects;
create policy "task-files delete" on storage.objects for delete to authenticated
  using (bucket_id = 'task-files');
